// Generated by https://quicktype.io

export interface OTResponse {
  id:                   number;
  tecnico:              Tecnico;
  seguimiento:          Seguimiento[];
  fecha_inicio:         string;
  observaciones:        string;
  marca_equipo:         string;
  modelo_equipo:        string;
  serie_equipo:         string;
  num_parte_componente: string;
  serie_componente:     string;
  fecha_entrega:        Date | null;
  is_active:            boolean;
  cliente:              Cliente;
  subrogante:           Tecnico | null;
}

export interface Cliente {
  id:     number;
  nombre: string;
}

export interface Seguimiento {
  id:                 number;
  ot:                 number;
  proceso:            number;
  estado:             boolean;
  estado_actividades: EstadoActividade[];
}

export interface EstadoActividade {
  id:             number;
  actividad:      number;
  estado:         boolean;
  estado_proceso: number;
}

export interface Tecnico {
  id:     number;
  nombre: string;
  email:  string;
}

export interface OTForm {
  id?:                  number;
  tecnico:              Tecnico;
  seguimiento:          Seguimiento[] | [];
  fecha_inicio:         string;
  observaciones:        string;
  marca_equipo:         string;
  modelo_equipo:        string;
  serie_equipo:         string;
  num_parte_componente: string;
  serie_componente:     string;
  fecha_entrega:        Date | null;
  is_active:            boolean;
  cliente:              number;
  subrogante:           Tecnico | null;
}

// Generated by https://quicktype.io

export interface ProcesosOT {
  id:          number;
  nombre:      string;
  actividades: Actividades[];
}

export interface Actividades {
  id:      number;
  nombre:  string;
  proceso: number;
}



