export interface OTResponse {
  id:                   number;
  fecha_inicio:         Date;
  cliente:              number | null;
  observaciones:        string;
  marca_equipo:         string;
  modelo_equipo:        string;
  serie_equipo:         string;
  num_parte_componente: string | null;
  serie_componente:     string | null;
  tecnico:              number | null;
  subrogante:           number | null;

  fecha_entrega:        Date | null;
  is_active:            boolean;
}

// Generated by https://quicktype.io

export interface ProcesosResponse {
  id:          number;
  nombre:      string;
  actividades: Actividades[];
}

export interface Actividades {
  id:      number;
  nombre:  string;
  proceso: number;
}
