interface InventoryStatus {
    label: string;
    value: string;
}
export interface Product {
    id?: string;
    code?: string;
    name?: string;
    description?: string;
    price?: number;
    quantity?: number;
    inventoryStatus?: InventoryStatus;
    category?: string;
    image?: string;
    rating?: number;
}
// Generated by https://quicktype.io

export interface DashboardData {
  tot_serv: number;
  tot_prod: number;
  tot_ot:   number;
  tot_cli:  number;
}
