interface InventoryStatus {
    label: string;
    value: string;
}
export interface Product {
    id?:              string;
    code?:            string;
    name?:            string;
    description?:     string;
    price?:           number;
    quantity?:        number;
    inventoryStatus?: InventoryStatus;
    category?:        string;
    image?:           string;
    rating?:          number;
}
// Generated by https://quicktype.io

export interface DashboardData {
  tot_serv:        number;
  tot_prod:        number;
  tot_ot:          number;
  tot_cli:         number;
  current_ot:      CurrentOt[];
}

export interface CurrentOt {
  id:                   number;
  fecha_inicio:         string;
  cliente_id:           number;
  observaciones:        string;
  marca_equipo:         string;
  modelo_equipo:        string;
  serie_equipo:         string;
  num_parte_componente: string;
  serie_componente:     string;
  tecnico_id:           null;
  subrogante_id:        null;
  usuario_id:           number;
  fecha_entrega:        null;
  is_active:            boolean;
  mes_inicio:           number;
}
