// Generated by https://quicktype.io

export interface UnidadesResponse {
  codigo: string;
  nombre: string;
}

// Generated by https://quicktype.io

export interface SubunidadResponse {
  codigo: string;
  unidad: UnidadesResponse;
  nombre: string;
}

// Generated by https://quicktype.io

export interface SubunidadForm {
  unidad_cod: string;
  codigo:     string;
  nombre:     string;
}


