// Generated by https://quicktype.io

// export interface ClienteResponse {
//   id?:           number;
//   comuna:        Comuna;
//   pais:          Pais;
//   razon_social:  string | null;
//   rut:           string;
//   sitio_web:     string;
//   telefono:      number;
//   direccion:     string;
//   codigo_postal: number | null;
// }


export interface ClienteForm {
  id?:           number;
  comuna_id:     number;
  pais_id?:      number | null;
  razon_social: string;
  rut:           string;
  sitio_web?:    string | null;
  telefono:      number;
  direccion:     string;
  codigo_postal?: number | null;
  estado?:       boolean;

}

// Generated by https://quicktype.io

export interface ClienteRES {
  id:            number;
  razon_social:  string;
  rut:           string;
  direccion:     string;
  comuna:        Comuna;
  sitio_web:     string;
  codigo_postal: number;
  telefono:      number;
  pais:          Pais;
  estado:        boolean;
  sucursales:    Sucursales[];
}

export interface Comuna {
  id:      number;
  nom_com: string;
  nom_reg: string;
}

export interface Pais {
  id:   number;
  name: string;
  code: string;
}

export interface Sucursales {
  id:        number;
  nombre:    string;
  direccion: string;
  cliente:   number;
  comuna:    Comuna;
  contactos: Contacto[];
}

export interface Contacto {
  id:       number;
  nombre:   string;
  apellido: string;
  correo:   string;
  telefono: number;
  sucursal: number;
}
