// Generated by https://quicktype.io

export interface ClienteResponse {
  id?:           number;
  comuna:        Comuna;
  pais:          Pais;
  razon_social:  string | null;
  rut:           string;
  sitio_web:     string;
  telefono:      number;
  direccion:     string;
  codigo_postal: number | null;
}

export interface Comuna {
  id:      number;
  nom_com: string;
  nom_reg: string;
}

export interface Pais {
  id:   number;
  name: string;
  code: string;
}

export interface ClienteForm {
  comuna_id:     number;
  pais?:         number | null;
  razon_social: string;
  rut:           string;
  sitio_web?:    string | null;
  telefono:      number;
  direccion:     string;
  codigo_postal?: number | null;
}
