export interface Producto{
  codigo: string;
  modelo: string | null;
  nombre: string;
  nota: string | null;
  fabricante: number;
  precio: number;
  estado?: boolean;
  fecha?: Date;
  imagen: string | null | File;
  stock: number;
}

// Generated by https://quicktype.io

export interface ProductosResponse {
  id:         number;
  fabricante: Fabricante;
  codigo:     string;
  modelo:     null | string;
  nombre:     string;
  nota:       string | null;
  precio:     number;
  estado:     boolean;
  fecha:      string;
  imagen:     null | string;
  stock:      number;
}

export interface Fabricante {
  id:     number;
  nombre: string;
}

export interface ProductoForm{
  id?: string;
  codigo: string;
  modelo: string | null;
  nombre: string;
  nota: string | null;
  fabricante_id: number;
  precio: number;
  estado?: boolean;
  fecha?: Date;
  imagen: File | null;
  stock: number;
}


