import { Fabricantes } from "../../../fabricantes/interfaces/fabricantes.model";


export interface Producto{
  codigo: string;
  modelo: string | null;
  nombre: string;
  nota: string | null;
  fabricante: Fabricantes;
  precio: number;
  estado?: boolean;
  fecha: Date;
  imagen: string | null;
  stock: number;
}

// Generated by https://quicktype.io

export interface ProductosResponse {
  id:         number;
  codigo:     string;
  modelo:     string | null;
  nombre:     string;
  nota:       string | null;
  precio:     number;
  estado:     boolean;
  fecha:      string;
  imagen:     string | null;
  stock:      number;
  fabricante: number;
}

export interface ProductoForm{
  // id?: string;
  codigo: string;
  modelo: string | null;
  nombre: string;
  nota: string | null;
  fabricante: number;
  precio: number;
  estado?: boolean;
  fecha?: Date;
  imagen: string | null;
  stock: number;
}
