// Generated by https://quicktype.io

export interface UsuariosResponse {
  id:           number;
  username:     string;
  email:        string;
  is_active:    boolean;
  is_staff:     boolean;
  is_superuser: boolean;
  nombre:       string;
  rut:          string;
}

export interface UsuariosForm {
  id?:           number;
  username:      string;
  email:         string;
  is_active?:    boolean;
  is_staff?:     boolean;
  is_superuser?: boolean;
  nombre:        string;
  rut:           string;
}
